# Site wide configuration

title: HoloMedia
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Giannis Variozidis & kat628
  bio: "MathQuiz Website."
  # Do not include the @ symbol in your Twitter username
  linkedin: Giannis-Variozidis
  github: jvario


theme: jekyll-theme-slate
